### ISSUE TITLE
データの出典

### ISSUE THREAD

**Issue by kaisugi** [yagays/ja-icd10#1]
このような便利なライブラリを公開していただき、ありがとうございます。

> 本レポジトリで利用しているデータは、下記ウェブサイトで公開されているものを利用しています。

> ICD10対応標準病名マスター　トップページ
> 標準病名マスター作業班　運用補助マスター

と書かれていますが、具体的に `data` ディレクトリ配下の各 `*.json.gz` ファイルはどこから取得したものなのか、教えていただけませんでしょうか。
「ICD10対応標準病名マスター」からダウンロードできるファイルは txt ファイルのみであるように思いましたので。

**Comment by yagays** [comment]
@HelloRusk こちらのissueを見逃しており、返信が遅れてしまい申し訳有りません。

`data`ディレクトリ配下のjsonは、`tools/`ディレクトリの各種コードで生成しております。`generate_data_from_byomei.py`の中に大本となるファイル名をハードコードしており、ここでは`byomei507`の各種ファイル(`nmain507.txt`, `mdfy507.txt`, `index507.txt`)を利用しております。

https://github.com/yagays/ja-icd10/blob/master/tools/generate_data_from_byomei.py

**Comment by kaisugi** [comment]
なるほど、JSONを生成するコードがあったのですね。見逃していました....
ご確認頂きありがとうございます！
